---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
- name: centos-5
  driver_config:
    box: opscode-centos-5.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.10"}]
- name: centos-6
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.11"}]
- name: debian-7
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.20"}]
- name: fedora-19
  driver_config:
    box: opscode-fedora-19
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.30"}]
- name: fedora-20
  driver_config:
    box: opscode-fedora-20
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.31"}]
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.40"}]
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.41"}]
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.42"}]
- name: ubuntu-13.10
  driver_config:
    box: opscode-ubuntu-13.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
    network:
      - ["private_network", {ip: "192.168.33.43"}]

suites:
- name: confluence-installer-mysql-no-java
  run_list:
  - recipe[confluence]
  attributes:
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo
- name: confluence-installer-mysql
  run_list:
  - recipe[java]
  - recipe[confluence]
  attributes:
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo
- name: confluence-installer-postgresql
  run_list:
  - recipe[java]
  - recipe[confluence]
  attributes:
    confluence:
      database:
        type: postgresql
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
